source 'https://rubygems.org'

#group :jekyll_plugins do
#  gem "jekyll-paginate"
#  gem "jekyll-feed"
#  gem "jekyll"
#end
gemspec

require 'json'
require 'open-uri'
#versions = JSON.parse(open('https://pages.github.com/versions.json').read)

gem 'github-pages', 219
